version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/sonic-server-common/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/sonic-server-controller/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/sonic-server-gateway/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/sonic-server-eureka/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/sonic-server-folder/"
    schedule:
      interval: "weekly"

