eureka:
  instance:
    instance-id: ${spring.application.name}(v${spring.version})-${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${SEC_NAME:sonic}:${SEC_PASSWORD:sonic}@${EUREKA_HOST:127.0.0.1}:${EUREKA_PORT:9090}/eureka/