spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${jdbc.url}:${jdbc.port}/${jdbc.database}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&serverTimezone=GMT%2b8
    username: ${jdbc.username}
    password: ${jdbc.password}
    initialization-mode: always
    schema:
      - classpath:data.sql

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml, classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  global-config:
    banner: false
  configuration:
    cache-enabled: false
    localCacheScope: STATEMENT

actable:
  model:
    pack: org.cloud.sonic.common.models.domain
  table:
    auto: update
  database:
    type: mysql