server:
  port: 0

springdoc:
  paths-to-exclude: /exchange/send,/agents/hubControl
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.cloud.sonic.controller
  default-flat-param-object: false

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: SonicQuartz
            instanceId: AUTO
          jobStore:
            isClustered: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

robot:
  client:
    host: http://${SONIC_SERVER_HOST:localhost}:${SONIC_SERVER_PORT:3000}
  img:
    success: "https://gitee.com/sonic-cloud/sonic-cloud/raw/main/src/assets/suc.png"
    warning: "https://gitee.com/sonic-cloud/sonic-cloud/raw/main/src/assets/warn.png"
    error: "https://gitee.com/sonic-cloud/sonic-cloud/raw/main/src/assets/fail.png"
