spring:
  ldap:
    base: ${ldap.base}
    username: ${ldap.username}
    password: ${ldap.password}
    urls: ${ldap.urls}
sonic:
  user:
    register:
      enable: true
    normal:
      enable: true
    ldap:
      enable: true
      userId: cn
      userBaseDN: ou=users
    token:
      secret: sonic
      expireDay: 14
