version: '3'
#you can add this for log debugging for every container.
#volumes:
#  - /home/sonic/logs/:/logs/
services:
  sonic-server-eureka:
    image: "zhouyixun/sonic-server-eureka:v1.0.0"
    hostname: sonic-server-eureka
    environment:
      - EUREKA_HOST=sonic-server-eureka
    networks:
      - sonic-network
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 6
  sonic-server-bus:
    image: "zhouyixun/sonic-server-bus:v1.0.0"
    environment:
      - PROFILE=prod
      - CONFIG_TYPE=git
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    depends_on:
      - sonic-server-eureka
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 6
  sonic-server-gateway:
    image: "zhouyixun/sonic-server-gateway:v1.0.0"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
    ports:
      - "8094:8094"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 6
  sonic-server-controller:
    image: "zhouyixun/sonic-server-controller:v1.0.0"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
      - sonic-server-gateway
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 6
  sonic-server-folder:
    image: "zhouyixun/sonic-server-folder:v1.0.0"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    #    volumes:
    #      - /home/sonic/keepFiles/:/keepFiles/
    #      - /home/sonic/imageFiles/:/imageFiles/
    #      - /home/sonic/recordFiles/:/recordFiles/
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
      - sonic-server-gateway
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 6
  sonic-server-task:
    image: "zhouyixun/sonic-server-task:v1.0.0"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
      - sonic-server-gateway
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 6
  sonic-server-transport:
    image: "zhouyixun/sonic-server-transport:v1.0.0"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
      - sonic-server-gateway
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 6

networks:
  sonic-network:
    driver: overlay