version: '3'
services:
  sonic-server-zookeeper:
    image: "zookeeper:latest"
    environment:
      - ZOO_TICK_TIME=100
      - ZOO_ADMINSERVER_ENABLED=false
    network_mode: "host"
  sonic-server-gateway:
    image: "sonicorg/sonic-server-gateway:v1.4.0-beta"
    environment:
      - SONIC_GATEWAY_PORT
      - ZOOKEEPER_HOST
      - ZOOKEEPER_PORT
      - SECRET_KEY
      - EXPIRE_DAY
    volumes:
      - ./logs/:/logs/
    depends_on:
      - sonic-server-zookeeper
    network_mode: "host"
    restart: on-failure
  sonic-server-controller:
    image: "sonicorg/sonic-server-controller:v1.4.0-beta"
    environment:
      - ZOOKEEPER_HOST
      - ZOOKEEPER_PORT
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_DATABASE
      - MYSQL_USERNAME
      - MYSQL_PASSWORD
      - SERVER_HOST
      - SONIC_GATEWAY_PORT
      - SONIC_CONTROLLER_PORT
      - CLIENT_HOST
      - DUBBO_PORT
      - SECRET_KEY
      - EXPIRE_DAY
      - REGISTER_ENABLE
      - NORMAL_USER_ENABLE
      - LDAP_USER_ENABLE
      - LDAP_USER_ID
      - LDAP_BASE_DN
      - LDAP_BASE
      - LDAP_USERNAME
      - LDAP_PASSWORD
      - LDAP_URL
    network_mode: "host"
    volumes:
      - ./logs/:/logs/
    depends_on:
      - sonic-server-zookeeper
    restart: on-failure
  sonic-server-folder:
    image: "sonicorg/sonic-server-folder:v1.4.0-beta"
    environment:
      - SERVER_HOST
      - SONIC_GATEWAY_PORT
      - SONIC_FOLDER_PORT
      - ZOOKEEPER_HOST
      - ZOOKEEPER_PORT
      - SECRET_KEY
      - EXPIRE_DAY
    network_mode: "host"
    volumes:
      - ./keepFiles/:/keepFiles/
      - ./imageFiles/:/imageFiles/
      - ./recordFiles/:/recordFiles/
      - ./packageFiles/:/packageFiles/
      - ./logs/:/logs/
    depends_on:
      - sonic-server-zookeeper
    restart: on-failure
  sonic-client-web:
    image: "sonicorg/sonic-client-web:v1.4.0-beta"
    environment:
      - SERVER_HOST=192.168.1.1
      - SONIC_GATEWAY_PORT=8094
    ports:
      - "3000:80"

