version: '3'
services:
  sonic-server-zookeeper:
    image: "zookeeper:latest"
    networks:
      - sonic-network
    ports:
      - "2181:2181"
  sonic-server-gateway:
    image: "sonicorg/sonic-server-gateway:v1.4.0-beta"
    environment:
      - SONIC_API_PORT=8094
      - ZOOKEEPER_HOST=192.168.1.1
      - ZOOKEEPER_PORT=2181
      - SECRET_KEY=sonic
      - EXPIRE_DAY=14
    networks:
      - sonic-network
    volumes:
      - ./logs/:/logs/
    depends_on:
      - sonic-server-zookeeper
    ports:
      - "8094:8094"
    restart: on-failure
  sonic-server-controller:
    image: "sonicorg/sonic-server-controller:v1.4.0-beta"
    environment:
      - ZOOKEEPER_HOST=192.168.1.1
      - ZOOKEEPER_PORT=2181
      - MYSQL_HOST=192.168.1.1
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=sonic
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Sonic!@#123
      - SERVER_HOST=192.168.1.1
      - SONIC_API_PORT=8094
      - DUBBO_PORT=20888
      - SECRET_KEY=sonic
      - EXPIRE_DAY=14
      - REGISTER_ENABLE=true
      - NORMAL_USER_ENABLE=true
      - LDAP_USER_ENABLE=true
      - LDAP_USER_ID=cn
      - LDAP_BASE_DN=ou=users
      - LDAP_BASE=ou=system
      - LDAP_USERNAME=uid=admin,ou=system
      - LDAP_PASSWORD=Sonic!@#123
      - LDAP_URL=ldap://127.0.0.1:10389
    networks:
      - sonic-network
    volumes:
      - ./logs/:/logs/
    depends_on:
      - sonic-server-zookeeper
    ports:
      - "20888:20888"
    restart: on-failure
  sonic-server-folder:
    image: "sonicorg/sonic-server-folder:v1.4.0-beta"
    environment:
      - SERVER_HOST=192.168.1.1
      - SONIC_API_PORT=8094
      - ZOOKEEPER_HOST=192.168.1.1
      - ZOOKEEPER_PORT=2181
      - SECRET_KEY=sonic
      - EXPIRE_DAY=14
    networks:
      - sonic-network
    volumes:
      - ./keepFiles/:/keepFiles/
      - ./imageFiles/:/imageFiles/
      - ./recordFiles/:/recordFiles/
      - ./packageFiles/:/packageFiles/
      - ./logs/:/logs/
    depends_on:
      - sonic-server-zookeeper
    restart: on-failure

networks:
  sonic-network:
    driver: bridge