version: '3'
services:
  sonic-server-zookeeper:
    image: "zookeeper:latest"
    environment:
      - JVMFLAGS="-Xmx1024m"
    networks:
      - sonic-network
    ports:
      - "2181:2181"
  sonic-server-gateway:
    image: "sonicorg/sonic-server-gateway:v1.4.0-beta"
    environment:
      - SONIC_API_PORT=8094
      - ZOOKEEPER_HOST=192.168.1.1
      - ZOOKEEPER_PORT=2181
      - SECRET_KEY=sonic
      - EXPIRE_DAY=14
    networks:
      - sonic-network
    volumes:
      - ./logs/:/logs/
    depends_on:
      - sonic-server-zookeeper
    ports:
      - "8094:8094"
    restart: on-failure
  sonic-server-controller:
    image: "sonicorg/sonic-server-controller:v1.4.0-beta"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    volumes:
      - ./logs/:/logs/
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
      - sonic-server-gateway
    restart: on-failure
  sonic-server-folder:
    image: "sonicorg/sonic-server-folder:v1.3.2-release"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    volumes:
      - ./keepFiles/:/keepFiles/
      - ./imageFiles/:/imageFiles/
      - ./recordFiles/:/recordFiles/
      - ./packageFiles/:/packageFiles/
      - ./logs/:/logs/
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
      - sonic-server-gateway
    restart: on-failure
  sonic-server-task:
    image: "sonicorg/sonic-server-task:v1.3.2-release"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    volumes:
      - ./logs/:/logs/
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
      - sonic-server-gateway
    restart: on-failure
  sonic-server-transport:
    image: "sonicorg/sonic-server-transport:v1.3.2-release"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    volumes:
      - ./logs/:/logs/
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
      - sonic-server-gateway
    ports:
      - "8095:8095"
    restart: on-failure

networks:
  sonic-network:
    driver: bridge