name: maven compile test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql database: 'sonic'
          mysql root password: 'Sonic!@#123'
          mysql user: 'root'
          mysql password: 'Sonic!@#123'
      - name: Validate and Compile with Maven
        run: mvn test
