name: release CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mkdir
      run: mkdir -p sonic-server-v1.5.0-beta/imageFiles sonic-server-v1.5.0-beta/keepFiles sonic-server-v1.5.0-beta/logs sonic-server-v1.5.0-beta/packageFiles sonic-server-v1.5.0-beta/recordFiles
    - name: copy
      run: cp .env docker-compose.yml sonic-server-v1.5.0-beta/
    - name: zip 
      uses: TheDoctor0/zip-release@0.6.2
      with: 
       filename: sonic-server-v1.5.0-beta.zip
       directory: sonic-server-v1.5.0-beta
    - name: tree
      run: tree
