name: release to github

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mkdir
      run: mkdir -p sonic-server-v1.5.0-beta/imageFiles sonic-server-v1.5.0-beta/keepFiles sonic-server-v1.5.0-beta/logs sonic-server-v1.5.0-beta/packageFiles sonic-server-v1.5.0-beta/recordFiles
    - name: copy
      run: cp .env docker-compose.yml sonic-server-v1.5.0-beta/
    - name: zip 
      uses: TheDoctor0/zip-release@0.6.2
      with: 
       filename: sonic-server-v1.5.0-beta.zip
       directory: sonic-server-v1.5.0-beta
    - name: mkdir2
      run: mkdir -p sonic-server-v1.5.0-beta-2/imageFiles sonic-server-v1.5.0-beta-2/keepFiles sonic-server-v1.5.0-beta-2/logs sonic-server-v1.5.0-beta-2/packageFiles sonic-server-v1.5.0-beta-2/recordFiles
    - name: copy
      run: cp .env docker-compose2.yml sonic-server-v1.5.0-beta-2/
    - name: rename
      run: mv sonic-server-v1.5.0-beta-2/docker-compose2.yml sonic-server-v1.5.0-beta-2/docker-compose.yml
    - name: zip 
      uses: TheDoctor0/zip-release@0.6.2
      with: 
       filename: sonic-server-v1.5.0-beta-2.zip
       directory: sonic-server-v1.5.0-beta-2
    - name: Upload To Github Release
      uses: svenstaro/upload-release-action@2.3.0
      with:
        file: sonic-server-v1.5.0-beta.zip,sonic-server-v1.5.0-beta-2.zip
